mkn:
  # file organization depends on <buckets>.
  # if buckets==daily: <root>/<middle>/<folders>/<yyyy>/<mm>/<dd>
  # if buckets==monthly: <root>/<middle>/<folders>/<yyyy>/<mm>
  root: /product_data/data/pay/Kenya/MKN/   
  branches:
    incoming: incoming
    archive: archive
    issues: incoming_with_issues
    logs: logs
  folders:
    - aerosol
    - ae33/data
    - meteo
    - tei49c
    - tei49i
    # - tei49i_2
    - g2401
  aerosol: 
    pattern: mkn_\d{8}T\d{6}Z.tar(|.gz)
    buckets: daily
    expected: 24
  ae33/data: 
    pattern: ae33-\d{12}.(zip|dat)
    buckets: daily
    expected: 144
  meteo: 
    pattern: VRXA00.\d{12}
    buckets: daily
    expected: 144
  tei49c: 
    pattern: tei49c-\d{12}.(zip|dat)
    buckets: daily
    expected: 144
  tei49i: 
    pattern: tei49i-\d{12}.(zip|dat)
    buckets: daily
    expected: 144
  # tei49i_2: 
  #   pattern: tei49i_2-\d{12}.(zip|dat)
  #   buckets: daily
  #   expected: 144
  g2401: 
    pattern: CFKADS2320-\d{8}-\d{6}Z-DataLog_User_Sync.zip
    buckets: daily
    expected: 24

nrb-brewer:
  root: /product_data/data/pay/ozone/arosa
  branches:
    incoming: incoming
  folders:
    - "071"
  "071": 
    pattern: B\d{5}.071
    buckets: None
    expected: 1
nrb-dobson:
  root: /product_data/data/pay/Kenya
  branches:
    uploads: uploads
  file_name: file_coverage_D018.json
  folders:
    - "prod"
  "prod": 
    pattern: D\d{7}.018
    buckets: yearly
    expected: 260
