import logging
import os
import shutil
import tempfile
import zipfile
from datetime import datetime

import chardet
#import numpy as np
import polars as pl

from toolbox.utils import pl_simplify_dtypes

MAPPINGS = pl.read_csv('cdp2_aurora_mappings.csv', has_header=True, dtypes=[pl.String]*4)

class NE300:
    config: dict
    name: str

    @classmethod
    def __init__(cls, config: dict, name: str='ne300'):
        """Initialize

        Args:
            config (dict): Configuration from config file
            name (str, optional): Instrument name, used in log files. Defaults to 'ne300'.
        """
        cls.logger: logging.Logger      # config['logging']
        cls.name: str
        cls.root: str                   # config['root']
        cls.incoming: str               # config['branches']['incoming']
        cls.archive: str                # config['branches']['archive']
        cls.issues: str                 # config['branches']['issues']
        cls.mappings: pl.DataFrame

        try:
            # configure logging
            _logger = f"{config['logging']}".split('.')[0]
            cls.logger = logging.getLogger(f"{_logger}.{__name__}")
            cls.logger.info("Initialize NE300 class.")

            cls.name = name
            cls.root = config['root']
            cls.incoming = config['branches']['incoming']
            cls.archive = config['branches']['archive']
            cls.issues = config['branches']['issues']

            cls.mappings = MAPPINGS
        except Exception as err:
            cls.logger.error(err)


    def extract_to_dataframe(self, file_path: str, dtm: str = 'dtm') -> pl.DataFrame:
        """
        Read file and extract to pl.DataFrame.
        
        Files in native format (retrieved directly from the instrument) have names starting 
        with the serial number, while files generated by mkndaq begin with 'ne300-'. 
        Files starting with '37' are assumed to have a header row and represent ACOEM variables. 
        The first column is labeled as 'dtm' and will be parsed as a datetime.

        Args:
            file_path (str): Full path to the file.
            dtm (str, optional): Name of the datetime column. Defaults to 'dtm'.

        Returns:
            pl.DataFrame: Processed DataFrame.
        """

        def read_csv(file_path: str, dtm: str = 'dtm', mappings: dict=self.mappings) -> pl.DataFrame:
            """Helper function to read a CSV and handle headers."""
            try:
                with open(file_path, 'rb') as f:
                    raw_data = f.read()
                    encoding = chardet.detect(raw_data)['encoding']

                # Read first row to check for header and ACOEM variable indicators
                with open(file_path, 'r', encoding=encoding) as file:
                    first_row = file.readline().strip().split(',')

                # Check if the first column contains a valid datetime or '37' header
                if is_datetime(first_row[0]):
                    df = pl.read_csv(file_path, encoding=encoding, has_header=False, try_parse_dates=True)
                    df = df.rename({df.columns[0]: dtm})
                elif first_row[0] == '37':
                    first_row[0] = dtm
                    first_row += ['operation', 'period']
                    df = pl.read_csv(file_path, encoding=encoding, has_header=False, skip_rows=1, try_parse_dates=True)
                    # df = df.with_columns(
                    #     pl.col(df.columns[0]).str.strptime(pl.Datetime, format="%Y-%m-%d %H:%M:%S").alias(dtm)
                    # )
                    mappings = dict(zip(df.columns, first_row))
                    df = df.rename(mappings)
                elif first_row[0] == 'Date & Time':
                    # Aurora native format file
                    df = pl.read_csv(file_path, encoding=encoding, has_header=True, try_parse_dates=True)
                    mappings = dict(zip(mappings["aurora_name"].to_list(), mappings["aurora_id"].to_list()))
                    df = df.rename({col: str(mappings[col]) for col in df.columns if col in mappings})
                    df = df.rename({'1': 'dtm'})
                    
                else:
                    return pl.DataFrame()

                return pl_simplify_dtypes(df)

            except Exception as err:
                print(f"Error reading CSV: {err}")
                return pl.DataFrame()

        def is_datetime(value: str) -> bool:
            """Check if a string value can be parsed as a datetime."""
            try:
                datetime.strptime(value, "%Y-%m-%d %H:%M:%S")
                return True
            except ValueError:
                return False

        # def extract_from_zip(file_path: str) -> pl.DataFrame:
        #     """Extract CSV from ZIP archive and process."""
        #     with zipfile.ZipFile(file_path, 'r') as zip_file:
        #         data_files = [f for f in zip_file.namelist() if f.endswith(('.dat', '.csv'))]
        #         if not data_files:
        #             raise ValueError("No data files found in the zip archive.")

        #         # Extract the single file to a temporary file
        #         temp_file = tempfile.NamedTemporaryFile(delete=False)
        #         with open(temp_file.name, 'wb') as fh:
        #             fh.write(zip_file.read(data_files[0]))

        #         return read_csv(temp_file.name, dtm)

        try:
            # If the file is a ZIP file, extract it to a temporary file and process it
            if zipfile.is_zipfile(file_path):
                with zipfile.ZipFile(file_path, 'r') as zip_file:
                    data_files = [f for f in zip_file.namelist() if f.endswith(('.dat', '.csv', '.txt'))]
                    if not data_files:
                        raise ValueError("No data files found in the zip archive.")
                    if len(data_files) > 1:
                        raise ValueError("More than 1 file found in the zip archive.")

                    # Extract the single file to a temporary file
                    temp_file = tempfile.NamedTemporaryFile(delete=False)
                    with open(temp_file.name, 'wb') as fh:
                        fh.write(zip_file.read(data_files[0]))

                    df = read_csv(temp_file.name, dtm)

                    os.remove(temp_file.name)

                return df

            # If it's not a ZIP file, process it directly
            return read_csv(file_path, dtm)

        except Exception as err:
            self.logger.error("%s: %s", file_path, err)
            return pl.DataFrame()


    def compile_files_to_parquet(self, source: str=str(), target: str='data/level1',
                                 dtm: str='dtm', archive: str=None, move_files_on_success: bool=True):
        """
        Harvest a folder and its sub-folders and compile the data found into .parquet files. 
        At this point, 2 file formats are supported, namely the Aurora file format and the mkndaq file format.
        The Aurora file format concerns files stored by the instrument, the mkndaq file format (v1) is the format generated by mkndaq.

        Args:
            source (str, optional): Folder to harvest. Defaults to str().
            target (str, optional): Folder for the resulting .parquet files. Defaults to 'data/level1'.
            dtm (str, optional): key of the timestamp column. Defaults to 'dtm'.
            archive (str, optional): Root path to directory where files will be archived. Sub-folders will be created corresponding to source. Defaults to None.
            issues (str, optional): Root path to directory where file that could not be processed are moved to. Defaults to None.
            by_year (bool, optional): Should .parquet files be organized by year. Defaults to True. NB: Currently not implemented.
        """
        try:
            if not source:
                source = os.path.join(self.root, self.incoming, self.name)

            df_native = pl.DataFrame()
            df_mkndaq = pl.DataFrame()
            if os.path.exists(source):
                for root, dirs, files in os.walk(source):
                    n = len(source) - len(root) + 1
                    relative_path = root[n:] if n < 0 else ""
                    if len(files)==0 and len(dirs)==0:
                        # remove empty folders
                        os.removedirs(root)
                    for file in files:
                        src = os.path.join(root, file)
                        if 'ne300-' in file:
                            # expect file to originate from MKNDAQ
                            _mkndaq = self.extract_to_dataframe(src)
                            if not _mkndaq.is_empty():
                                try:
                                    df_mkndaq = pl.concat([df_mkndaq, _mkndaq], how='diagonal')
                                    if archive and move_files_on_success:
                                        dst = os.path.join(archive, relative_path)
                                        os.makedirs(dst, exist_ok=True)
                                        dst = os.path.join(dst, file)
                                    else:
                                        dst = str()
                                except Exception as err:
                                    self.logger.error("Issue concatenating data frames: %s produced exception: %s", file, err)
                                    dst = os.path.join(root, file).replace(self.incoming, self.issues)
                            else:
                                dst = os.path.join(root, file).replace(self.incoming, self.issues)
                        else:
                            # expect file to originate from instrument natively
                            _native = self.extract_to_dataframe(src)
                            if not _native.is_empty():
                                try:
                                    df_native = pl.concat([df_native, _native], how='diagonal')
                                    if archive and move_files_on_success:
                                        dst = os.path.join(archive, relative_path)
                                        os.makedirs(dst, exist_ok=True)
                                        dst = os.path.join(dst, file)
                                    else:
                                        dst = str()
                                except Exception as err:
                                    self.logger.error("Issue concatenating data frames: %s produced exception: %s", file, err)
                                    dst = os.path.join(root, file).replace(self.incoming, self.issues)
                            else:
                                dst = os.path.join(root, file).replace(self.incoming, self.issues)

                        if dst:
                            os.makedirs(os.path.dirname(dst), exist_ok=True)
                            shutil.move(src=src, dst=dst)

                # verify if .parquet already exist, amend and retain unique values
                for file, df in {'ne300_native.parquet': df_native, 'ne300_mkndaq.parquet': df_mkndaq}.items():
                    target_file = os.path.join(target, file)
                    try:
                        os.makedirs(os.path.dirname(target_file), exist_ok=True)
                        if os.path.exists(target_file):
                            df = pl.concat([pl.read_parquet(target_file),
                                            df], how='diagonal')
                        df = df.unique().sort(by=dtm)
                        df.write_parquet(target_file)
                    except Exception as err:
                        self.logger.error("update parquet file: %s produced error: %s", file, err)
                        df_native.write_parquet(os.path.join(target, '_native.parquet'))
                        df_mkndaq.write_parquet(os.path.join(target, '_mkndaq.parquet'))

        except Exception as err:
            self.logger.error("file: %s produced error: %s", file, err)
