import logging
import os
import re
import shutil
import tempfile
import zipfile
from datetime import datetime
from io import BytesIO
from pathlib import Path

import chardet
import polars as pl

from toolbox.utils import pl_simplify_dtypes

MAPPINGS = pl.read_csv('cdp2_aurora_mappings.csv', has_header=True, dtypes=[pl.String]*4)

class NE300:
    config: dict
    name: str

    def __init__(self, config: dict, name: str='ne300'):
        """Initialize

        Args:
            config (dict): Configuration from config file
            name (str, optional): Instrument name, used in log files. Defaults to 'ne300'.
        """
        self.logger: logging.Logger      # config['logging']
        self.name: str
        self.root: str                   # config['root']
        self.incoming: str               # config['branches']['incoming']
        self.archive: str                # config['branches']['archive']
        self.issues: str                 # config['branches']['issues']
        self.mappings: pl.DataFrame

        try:
            # configure logging
            _logger = f"{config['logging']}".split('.')[0]
            self.logger = logging.getLogger(f"{_logger}.{__name__}")
            self.logger.info("Initialize NE300 class.")

            self.name = name
            self.root = config['root']
            self.incoming = config['branches']['incoming']
            self.archive = config['branches']['archive']
            self.issues = config['branches']['issues']

            self.mappings = MAPPINGS
        except Exception as err:
            self.logger.error(err)


    def extract_to_dataframe(self, file_path: str, dtm: str = 'dtm') -> pl.DataFrame:
        """
        Read file and extract to pl.DataFrame.
        
        Files in native format (retrieved directly from the instrument) have names starting 
        with the serial number, while files generated by mkndaq begin with 'ne300-'. 
        Files starting with '37' are assumed to have a header row and represent ACOEM variables. 
        The first column is labeled as 'dtm' and will be parsed as a datetime.

        Args:
            file_path (str): Full path to the file.
            dtm (str, optional): Name of the datetime column. Defaults to 'dtm'.

        Returns:
            pl.DataFrame: Processed DataFrame.
        """

        def read_csv(file_path: str, dtm: str='dtm', mappings: dict=self.mappings) -> pl.DataFrame:
            """Helper function to read a CSV and handle headers."""
            try:
                with open(file_path, 'rb') as f:
                    raw_data = f.read()
                    encoding = chardet.detect(raw_data)['encoding']

                # Read first row to check for header and ACOEM variable indicators
                with open(file_path, 'r', encoding=encoding) as file:
                    first_row = file.readline().strip().split(',')

                # Check if the first column contains a valid datetime or '37' header
                if is_datetime(first_row[0]):
                    df = pl.read_csv(file_path, encoding=encoding, has_header=False, try_parse_dates=True)
                    df = df.rename({df.columns[0]: dtm})
                elif first_row[0] == '37':
                    first_row[0] = dtm
                    first_row += ['operation', 'period']
                    df = pl.read_csv(file_path, encoding=encoding, has_header=False, skip_rows=1, try_parse_dates=True)
                    # df = df.with_columns(
                    #     pl.col(df.columns[0]).str.strptime(pl.Datetime, format="%Y-%m-%d %H:%M:%S").alias(dtm)
                    # )
                    mappings = dict(zip(df.columns, first_row))
                    df = df.rename(mappings)
                elif first_row[0] == 'Date & Time':
                    # Aurora native format file
                    df = pl.read_csv(file_path, encoding=encoding, has_header=True, try_parse_dates=True)
                    mappings = dict(zip(mappings["aurora_name"].to_list(), mappings["aurora_id"].to_list()))
                    df = df.rename({col: str(mappings[col]) for col in df.columns if col in mappings})
                    df = df.rename({'1': 'dtm'})
                    
                else:
                    return pl.DataFrame()

                return pl_simplify_dtypes(df)

            except Exception as err:
                print(f"Error reading CSV: {err}")
                return pl.DataFrame()

        def is_datetime(value: str) -> bool:
            """Check if a string value can be parsed as a datetime."""
            try:
                datetime.strptime(value, "%Y-%m-%d %H:%M:%S")
                return True
            except ValueError:
                return False

        # def extract_from_zip(file_path: str) -> pl.DataFrame:
        #     """Extract CSV from ZIP archive and process."""
        #     with zipfile.ZipFile(file_path, 'r') as zip_file:
        #         data_files = [f for f in zip_file.namelist() if f.endswith(('.dat', '.csv'))]
        #         if not data_files:
        #             raise ValueError("No data files found in the zip archive.")

        #         # Extract the single file to a temporary file
        #         temp_file = tempfile.NamedTemporaryFile(delete=False)
        #         with open(temp_file.name, 'wb') as fh:
        #             fh.write(zip_file.read(data_files[0]))

        #         return read_csv(temp_file.name, dtm)

        try:
            # If the file is a ZIP file, extract it to a temporary file and process it
            if zipfile.is_zipfile(file_path):
                with zipfile.ZipFile(file_path, 'r') as zf:
                    data_file = [f for f in zf.namelist() if f.endswith(('.dat', '.csv', '.txt'))]
                    if not data_file:
                        raise ValueError("No data files found in the zip archive.")
                    if len(data_file) > 1:
                        raise ValueError("More than 1 file found in the zip archive.")

                    # Extract the single file to a temporary file
                    # temp_file = tempfile.NamedTemporaryFile(delete=False)
                    # with open(temp_file.name, 'wb') as fh:
                    #     fh.write(zip_file.read(data_files[0]))
                    with zf.open(data_file[0]) as fh:
                        file_bytes = fh.read()
                        file_buffer = BytesIO(file_bytes)
                        first_line = file_buffer.readline().decode('utf-8').strip()
                        file_buffer.seek(0)  # Reset pointer to read the file again
                        
                        # Check if the first field is '37'
                        if first_line.split(',')[0] == '37':
                            has_header = False
                            skip_rows = 1
                            new_columns = first_line.replace('37', dtm).split(',') + ['operation', 'interval']
                        
                        # Read the file into a polars DataFrame
                        df = pl.read_csv(file_buffer, has_header=has_header, skip_rows=skip_rows, new_columns=new_columns)

                # Convert the first column to datetime
                df = df.with_columns(pl.col(df.columns[0]).str.to_datetime("%Y-%m-%d %H:%M:%S%.f", time_unit='us').alias(df.columns[0]))
                
                return df

            # If it's not a ZIP file, process it directly
            return read_csv(file_path, dtm)

        except Exception as err:
            self.logger.error("%s: %s", file_path, err)
            return pl.DataFrame()


    def _move_file(self, src: str, dst: str, split: str = "month") -> Path:
        """create destination path and move file.

        Args:
            src (str): Full path to source file.
            dst (str): Destination root path.
            split (str, optional): File organization in dst. One of 'year|month|day'. Defaults to 'month'.

        Returns:
            Path: Full path to destination.
        """
        try:
            src = Path(src)
            match = re.search(r"-(\d{4})(\d{2})(\d{2})\d{2}\d{2}\.(zip|dat|csv|txt)$", src.name)

            if not match:
                # print(f"shutil.move({src}, {Path(dst) / src.name}")
                shutil.move(src, Path(dst) / src.name)
                return Path(dst) / src.name  # Default case if no timestamp match

            year, month, day = match.group(1, 2, 3)
            dst = Path(dst) / year / month / day
            split_map = {
                "year": dst.parents[2],
                "month": dst.parent,
                "day": dst,
            }
            dst = split_map.get(split, dst)
            dst.mkdir(parents=True, exist_ok=True)

            # print(f"shutil.move({src}, {Path(dst) / src.name}")
            shutil.move(src, dst / src.name)            
            self.logger.info(f"file moved: {src} > {dst / src.name}")
            
            return dst / src.name
        
        except Exception as err:
            self.logger.error("_move_file: %s produced exception: %s", src, err)
            

    def append_parquet(self, df: pl.DataFrame, target: Path, dtm: str="dtm",
                       split: str="month", file_name: str="ne300_mkndaq.parquet") -> Path:
        try:
            assert split in {"year", "month", "day"}, "split must be 'year', 'month', or 'day'"

            df = pl_simplify_dtypes(df)#.with_columns(pl.col(dtm).cast(pl.Datetime('us', 'UTC'))))
            start_date, end_date = df[dtm].min().date(), df[dtm].max().date()
            date_ranges = pl.date_range(start_date, end_date, interval="1d", eager=True)

            for date in date_ranges:
                year, month, day = str(date.year), f"{date.month:02d}", f"{date.day:02d}"
                dst = target / year / month / day
                split_map = {
                    "year": dst.parents[2],
                    "month": dst.parent,
                    "day": dst,
                }
                dst = split_map.get(split, dst)
                dst.mkdir(parents=True, exist_ok=True)

                # if split == "year":
                #     folder_path = folder_path.parents[2]
                # elif split == "month":
                #     folder_path = folder_path.parent

                df_filtered = df.filter(
                    (pl.col(dtm).dt.year() == date.year)
                    & (split != "year" or (pl.col(dtm).dt.month() == date.month))
                    & (split != "month" or (pl.col(dtm).dt.date() == date))
                )   # [TODO] handle case where df extends across split?

                file_path = dst / file_name
                if file_path.exists():
                    df_existing = pl.read_parquet(file_path)
                    # df_existing = df_existing.with_columns(pl.col('dtm').str.to_datetime())
                    rows_existing = len(df_existing)
                    df_combined = pl.concat([df_existing, df_filtered], how="diagonal").unique().sort(dtm)
                else:
                    rows_existing = 0
                    df_combined = df_filtered.unique().sort(dtm)
                rows_combined = len(df_combined)

                df_combined.write_parquet(file_path)
            
            self.logger.info(f"{file_path}: rows added: {rows_combined - rows_existing}")
            return file_path
        except Exception as err:
            self.logger.error("append_parquet: %s produced exception: %s", target / file_name, err)
            return str()


    def compile_files_to_parquet(self, source: str=str(), target: str=str(),
                                 move_processed_files: bool=True, archive: str=str(), issues: str=str(), 
                                 split: str="month", dtm: str="dtm"):
        """
        Harvest a folder and its sub-folders, compile data into .parquet files, and organize them.
        
        Args:
            source (str, optional): Folder to harvest. Defaults to self.root / self.incoming / self.name.
            target (str, optional): Folder for .parquet files. Defaults to 'data/level1'.
            dtm (str, optional): Timestamp column name. Defaults to 'dtm'.
            move_processed_files (bool, optional): Move processed files? Defaults to True.
        """
        try:
            source = Path(source or (Path(self.root) / self.incoming / self.name))
            archive = Path(archive or (Path(self.root) / self.archive / self.name))
            issues = Path(issues or (Path(self.root) / self.issues / self.name))
            target = Path(target or (Path(self.root) / target))
            if not source.exists():
                return

            src = Path()
            for root, dirs, files in os.walk(source):
                for file in files:
                    _dst = issues  # Default destination
                    src = Path(root) / file
                    df = self.extract_to_dataframe(file_path=src, dtm=dtm)

                    if not df.is_empty():
                        file_name = f"{self.name}.parquet" if self.name in src.name else f"{self.name}_native.parquet"
                        parquet = self.append_parquet(df=df, target=target, dtm=dtm, split=split, file_name=file_name)
                        if parquet:
                            _dst = archive  # Success
                        else:
                            continue
                    if move_processed_files:
                        dst = self._move_file(src=src, dst=_dst, split=split)

                if Path(root) != source:
                    try:
                        Path(root).rmdir()
                    except OSError:
                        pass

        except Exception as err:
            self.logger.error("compile_files_to_parquet: file: %s produced error: %s", src, err)


    # def _create_dst_path(self, src: str, dst: str, split: str='month') -> str:
    #     """Create a full destination path for a file.

    #     Args:
    #         src (str): full path to source file. Must contain self.incoming
    #         dst (str): relative path of destination, either self.archive or self.issues
    #         split (str, optional): File organization in dst. One of 'yearly|monthly|daily'. Defaults to 'monthly'.

    #     Returns:
    #         str: full path to destination
    #     """
    #     # extract year and month from file name
    #     _basename = os.path.basename(src)
    #     match = re.search(r'-(\d{4})(\d{2})(\d{2})\d{2}\d{2}\.(zip|dat|csv|txt)$', _basename)
    #     if match:
    #         year = match.group(1)   # 4-digit year as string
    #         month = match.group(2)  # 2-digit month as string (keeps leading zero)
    #         day = match.group(3)    # 2-digit day as string (keeps leading zero)
    #     else:
    #         print("we shouldn't be here!")

    #     dst = os.path.dirname(src).replace(self.incoming, dst)
    #     dst = dst.replace(os.path.join(year, month, day), '')
    #     _dst = str()
    #     if split=='year':
    #         _dst = os.path.join(dst, year)
    #     if split=='month':
    #         _dst = os.path.join(dst, year, month)
    #     elif split=='day':
    #         _dst = os.path.join(dst, year, month, day)
    #     if _dst:
    #         os.makedirs(_dst, exist_ok=True)
    #         _dst = os.path.join(_dst, _basename)
    #     return _dst
    

    # def append_parquet(self, df: pl.DataFrame, target: str='data/level1', dtm: str='dtm', 
    #                    split: str='month', file_name: str="ne300_mkndaq.parquet") -> str:
    #     try:
    #         assert split in {"year", "month", "day"}, "split must be 'year', 'month', or 'day'"

    #         # Ensure dtm is a proper datetime column
    #         df = df.with_columns(pl.col(dtm).cast(pl.Datetime))

    #         # Extract start and end timestamps
    #         start_date = df[dtm].min().date()
    #         end_date = df[dtm].max().date()

    #         # Generate date range
    #         date_ranges = pl.date_range(start_date, end_date, interval="1d", eager=True)

    #         # Process data by split type
    #         for date in date_ranges:
    #             year = str(date.year)
    #             month = f"{date.month:02d}"
    #             day = f"{date.day:02d}"

    #             if split == "year":
    #                 df_filtered = df.filter(pl.col(dtm).dt.year() == date.year)
    #                 folder_path = os.path.join(self.root, target, year)
    #             elif split == "month":
    #                 df_filtered = df.filter(
    #                     (pl.col(dtm).dt.year() == date.year) & 
    #                     (pl.col(dtm).dt.month() == date.month)
    #                 )
    #                 folder_path = os.path.join(self.root, target, year, month)
    #             else:  # split == "day"
    #                 df_filtered = df.filter(pl.col(dtm).dt.date() == date)
    #                 folder_path = os.path.join(self.root, target, year, month, day)

    #             # Define file path
    #             file_path = os.path.join(folder_path, file_name)

    #             # Ensure the directory exists
    #             os.makedirs(folder_path, exist_ok=True)

    #             # If parquet file exists, read it and append the new data
    #             if file_path.exists():
    #                 df_existing = pl.read_parquet(file_path)
    #                 df_combined = pl.concat([df_existing, df_filtered], how='diagonal').unique().sort(dtm)
    #             else:
    #                 df_combined = df_filtered.unique().sort(dtm)

    #             # Save the updated DataFrame
    #             df_combined.write_parquet(file_path)

    #         return file_path

    #     except Exception as err:
    #         print(err)


    # def compile_files_to_parquet(self, source: str=str(), target: str='data/level1', dtm: str='dtm', 
    #                              move_processed_files: bool=True, split: str='monthly'):
    #     """
    #     Harvest a folder and its sub-folders and compile the data found into .parquet files. 
    #     At this point, 2 file formats are supported, namely the Aurora file format and the mkndaq file format.
    #     The Aurora file format concerns files stored by the instrument, the mkndaq file format (v1) is the format generated by mkndaq.
    #     1) establish list of files to process using os.walk()
    #     2) read file to pl.Dataframe, move to issues if error if move_processed_files==True
    #     3) open corresponding existing .parquet file and append new data, select unique values, sort by dtm, save; or save as new .parquet file.
    #     4) archive file if move_processed_files==True
        
    #     Args:
    #         source (str, optional): Folder to harvest. Defaults to str().
    #         target (str, optional): Folder for the resulting .parquet files. Defaults to 'data/level1'.
    #         dtm (str, optional): key of the timestamp column. Defaults to 'dtm'.
    #         move_processed_files (str, optional): Should processed files be moved? Defaults to True.
    #     """
    #     try:
    #         if not source:
    #             source = os.path.join(self.root, self.incoming, self.name)
    #         else:
    #             source = os.path.join(source, self.name)

    #         file_path = str()
    #         if os.path.exists(source):
    #             for root, dirs, files in os.walk(source):
    #                 for file in files:
    #                     src = os.path.join(root, file)
    #                     _dst = self.issues              # default destination
    #                     df = self.extract_to_dataframe(file_path=src)
    #                     if not df.is_empty():
    #                         file_name = 'ne300_mkndaq.parquet' if 'ne300-' in file else 'ne300_native.parquet'                               
    #                         try:
    #                             file_path = self.append_parquet(df=df, target=target, split=split)
    #                             _dst = self.archive     # success
    #                         except Exception as err:
    #                             self.logger.error("concatenate data frames: %s produced exception: %s", file, err)
    #                             _dst = self.issues

    #                     if move_processed_files and dst:
    #                         dst = self._create_dst_path(src=src, dst=_dst, split=split)
    #                         os.makedirs(os.path.dirname(dst), exist_ok=True)
    #                         shutil.move(src=src, dst=dst)

    #                 # remove empty folders, except source itself
    #                 if root != source:
    #                     try:
    #                         os.removedirs(root)
    #                     except OSError:
    #                         pass

    #     except Exception as err:
    #         self.logger.error("file: %s produced error: %s", file, err)


    # def compile_files_to_parquet_v2(self, source: str=str(), target: str='data/level1', dtm: str='dtm', 
    #                              move_processed_files: bool=True, split: str='monthly'):
    #     """
    #     Harvest a folder and its sub-folders and compile the data found into .parquet files. Organize .parquet files in monthly sub-folders.
    #     At this point, 2 file formats are supported, namely the Aurora file format and the mkndaq file format.
    #     The Aurora file format concerns files stored by the instrument, the mkndaq file format (v1) is the format generated by mkndaq.

    #     Args:
    #         source (str, optional): Folder to harvest. Defaults to str().
    #         target (str, optional): Folder for the resulting .parquet files. Defaults to 'data/level1'.
    #         dtm (str, optional): key of the timestamp column. Defaults to 'dtm'.
    #         move_processed_files (str, optional): Should processed files be moved? Defaults to True.
    #     """
    #     try:
    #         if not source:
    #             source = os.path.join(self.root, self.incoming, self.name)
    #         else:
    #             source = os.path.join(source, self.name)

    #         df_native = pl.DataFrame()
    #         df_mkndaq = pl.DataFrame()
    #         if os.path.exists(source):
    #             for root, dirs, files in os.walk(source):
    #                 for file in files:
    #                     src = os.path.join(root, file)
    #                     if 'ne300-' in file:
    #                         # expect file to originate from MKNDAQ
    #                         _mkndaq = self.extract_to_dataframe(src)
    #                         dst = str()
    #                         if not _mkndaq.is_empty():
    #                             try:
    #                                 df_mkndaq = pl.concat([df_mkndaq, _mkndaq], how='diagonal')
    #                                 if move_processed_files:
    #                                     dst = self._create_dst_path(src=src, dst=self.archive, split=split)
    #                             except Exception as err:
    #                                 self.logger.error("concatenate data frames: %s produced exception: %s", file, err)
    #                                 if move_processed_files:
    #                                     dst = self._create_dst_path(src=src, dst=self.issues, split=split)
    #                         else:
    #                             if move_processed_files:
    #                                 dst = self._create_dst_path(src=src, dst=self.issues, split=split)
    #                     else:
    #                         # expect file to originate from instrument natively
    #                         _native = self.extract_to_dataframe(src)
    #                         if not _native.is_empty():
    #                             try:
    #                                 df_native = pl.concat([df_native, _native], how='diagonal')
    #                                 if move_processed_files:
    #                                     dst = self._create_dst_path(src=src, dst=self.archive, split=split)
    #                             except Exception as err:
    #                                 self.logger.error("Issue concatenating data frames: %s produced exception: %s", file, err)
    #                                 if move_processed_files:
    #                                     dst = self._create_dst_path(src=src, dst=self.issues, split=split)
    #                         else:
    #                             if move_processed_files:
    #                                 dst = self._create_dst_path(src=src, dst=self.issues, split=split)

    #                     if move_processed_files and dst:
    #                         os.makedirs(os.path.dirname(dst), exist_ok=True)
    #                         shutil.move(src=src, dst=dst)

    #                 # remove empty folders, except source itself
    #                 if root != source:
    #                     try:
    #                         os.removedirs(root)
    #                     except OSError:
    #                         pass

    #                 # verify if .parquet already exist, and if so, amend dataframe and retain unique values
    #                 for file, df in {'ne300_native.parquet': df_native, 'ne300_mkndaq.parquet': df_mkndaq}.items():
    #                     if not df.is_empty():
    #                         # target_dir = os.path.join(target, year, month)
    #                         target_dir = root.replace(self.incoming, target)
    #                         os.makedirs(target_dir, exist_ok=True)
    #                         target_file = os.path.join(target_dir, file)
    #                         if os.path.exists(target_file):
    #                             try:
    #                                 df = pl.concat([pl.read_parquet(target_file), df], how='diagonal')
    #                                 df = df.unique().sort(by=dtm)
    #                                 df.write_parquet(target_file)
    #                             except Exception as err:
    #                                 self.logger.error("update file: %s produced error: %s", file, err)
    #                                 pass
    #                         else:
    #                             df = df.unique().sort(by=dtm)
    #                             df.write_parquet(target_file)
    #                         # df_native.write_parquet(os.path.join(target, '_native.parquet'))
    #                         # df_mkndaq.write_parquet(os.path.join(target, '_mkndaq.parquet'))

    #     except Exception as err:
    #         self.logger.error("file: %s produced error: %s", file, err)


    # def compile_files_to_parquet_v1(self, source: str=str(), target: str='data/level1',
    #                              dtm: str='dtm', archive: str=None, move_files_on_success: bool=True):
    #     """
    #     Harvest a folder and its sub-folders and compile the data found into .parquet files. Organize .parquet files in monthly sub-folders.
    #     At this point, 2 file formats are supported, namely the Aurora file format and the mkndaq file format.
    #     The Aurora file format concerns files stored by the instrument, the mkndaq file format (v1) is the format generated by mkndaq.

    #     Args:
    #         source (str, optional): Folder to harvest. Defaults to str().
    #         target (str, optional): Folder for the resulting .parquet files. Defaults to 'data/level1'.
    #         dtm (str, optional): key of the timestamp column. Defaults to 'dtm'.
    #         archive (str, optional): Root path to directory where files will be archived. Sub-folders will be created corresponding to source. Defaults to None.
    #         issues (str, optional): Root path to directory where file that could not be processed are moved to. Defaults to None.
    #         by_year (bool, optional): Should .parquet files be organized by year. Defaults to True. NB: Currently not implemented.
    #     """
    #     try:
    #         if not source:
    #             source = os.path.join(self.root, self.incoming, self.name)

    #         df_native = pl.DataFrame()
    #         df_mkndaq = pl.DataFrame()
    #         if os.path.exists(source):
    #             for root, dirs, files in os.walk(source):
    #                 n = len(source) - len(root) + 1
    #                 relative_path = root[n:] if n < 0 else ""
    #                 # if len(files)==0 and len(dirs)==0:
    #                 # remove empty folders
    #                 try:
    #                     os.removedirs(root)
    #                 except OSError:
    #                     pass

    #                 for file in files:
    #                     src = os.path.join(root, file)
    #                     if 'ne300-' in file:
    #                         # expect file to originate from MKNDAQ
    #                         _mkndaq = self.extract_to_dataframe(src)
    #                         if not _mkndaq.is_empty():
    #                             try:
    #                                 df_mkndaq = pl.concat([df_mkndaq, _mkndaq], how='diagonal')
    #                                 if archive and move_files_on_success:
    #                                     dst = os.path.join(archive, relative_path)
    #                                     os.makedirs(dst, exist_ok=True)
    #                                     dst = os.path.join(dst, file)
    #                                 else:
    #                                     dst = str()
    #                             except Exception as err:
    #                                 self.logger.error("Issue concatenating data frames: %s produced exception: %s", file, err)
    #                                 dst = os.path.join(root, file).replace(self.incoming, self.issues)
    #                         else:
    #                             dst = os.path.join(root, file).replace(self.incoming, self.issues)
    #                     else:
    #                         # expect file to originate from instrument natively
    #                         _native = self.extract_to_dataframe(src)
    #                         if not _native.is_empty():
    #                             try:
    #                                 df_native = pl.concat([df_native, _native], how='diagonal')
    #                                 if archive and move_files_on_success:
    #                                     dst = os.path.join(archive, relative_path)
    #                                     os.makedirs(dst, exist_ok=True)
    #                                     dst = os.path.join(dst, file)
    #                                 else:
    #                                     dst = str()
    #                             except Exception as err:
    #                                 self.logger.error("Issue concatenating data frames: %s produced exception: %s", file, err)
    #                                 dst = os.path.join(root, file).replace(self.incoming, self.issues)
    #                         else:
    #                             dst = os.path.join(root, file).replace(self.incoming, self.issues)

    #                     if dst:
    #                         os.makedirs(os.path.dirname(dst), exist_ok=True)
    #                         shutil.move(src=src, dst=dst)

    #             # verify if .parquet already exist, amend and retain unique values
    #             for file, df in {'ne300_native.parquet': df_native, 'ne300_mkndaq.parquet': df_mkndaq}.items():
    #                 target_file = os.path.join(target, file)
    #                 try:
    #                     os.makedirs(os.path.dirname(target_file), exist_ok=True)
    #                     if os.path.exists(target_file):
    #                         df = pl.concat([pl.read_parquet(target_file),
    #                                         df], how='diagonal')
    #                     df = df.unique().sort(by=dtm)
    #                     df.write_parquet(target_file)
    #                 except Exception as err:
    #                     self.logger.error("update parquet file: %s produced error: %s", file, err)
    #                     # df_native.write_parquet(os.path.join(target, '_native.parquet'))
    #                     # df_mkndaq.write_parquet(os.path.join(target, '_mkndaq.parquet'))

    #     except Exception as err:
    #         self.logger.error("file: %s produced error: %s", file, err)
