import os
import logging
import polars as pl
import zipfile
import shutil

MAPPINGS = pl.read_csv('cdp2_aurora_mappings.csv', has_header=True, dtypes=[pl.String]*4)

class NE300:
    def __init__(self, config: dict, name: str='ne300'):
        """
        Initialize class.

        Args:
            config (dict): at least the following elements are expected:
                            - config['root']
                            - config['logging']
                            - config['branches']['incoming']
                            - config['branches']['archive']
                            - config['branches']['issues']
        """
        try:
            # configure logging
            _logger = f"{config['logging']}".split('.')[0]
            self.logger = logging.getLogger(f"{_logger}.{__name__}")
            self.logger.info("Initialize NE300 class.")
            
            self.name = name
            self.root = config['root']
            self.incoming = config['branches']['incoming']
            self.archive = config['branches']['archive']
            self.issues = config['branches']['issues']

            self.mappings = MAPPINGS
        except Exception as err:
            self.logger.error(err)
            pass


    def extract_to_dataframe(self, file: str, dtm: str='dtm', log: bool=True) -> pl.DataFrame:
        """
        Read file and extract to pl.DataFrame. Columns are identified based on filename.
        Files directly retrieved from the instrument (micrSD card or USB stick) have names that start with the serial number of the instrument, e.g., 00...
        Files generated with mkndaq have names that begin with ne300-...

        Args:
            file (str): full path to file.
            dtm (str, optional): name of dateTime column. Defaults to 'dtm'.
            log (bool, optional): Should progress be logged? Defaults to True.

        Returns:
            pl.DataFrame: _description_
        """
        try:
            if 'ne300' in os.path.basename(file):
                if zipfile.is_zipfile(file):
                    file = zipfile.ZipFile(file).read(os.path.basename(file.replace('.zip', '.dat')))
                df = pl.read_csv(source=file, has_header=False, try_parse_dates=True)
                dtypes = [pl.Datetime(time_unit='us', time_zone=None)] + [pl.Float64]*45 + [pl.String] + [pl.Int64]

                if df.dtypes==dtypes:
                    _mappings = self.mappings.filter(pl.col('mkndaq_id').is_in(df.columns))
                    mapping = dict(zip(_mappings['mkndaq_id'], _mappings['aurora_id']))
                    df = df.rename(mapping=mapping)                    
                    return df
                else:
                    raise ValueError(f"unexpected dtypes found: {df.dtypes}")

            else:
                # file is expected to originate from the instrument directly (microSD card or USB stick)
                df = pl.read_csv(source=file, has_header=True, try_parse_dates=True)
                _mappings = self.mappings.filter(pl.col('aurora_name').is_in(df.columns))
                mapping = dict(zip(_mappings['aurora_name'], _mappings['aurora_id']))
                # mapping.pop(None)
                df = df.rename(mapping=mapping)
                df = df.rename({'1': dtm})
                
                # drop the empty column at the end
                df.drop_in_place("")

            return df

        except Exception as err:
            self.logger.error(f"{file}: {err}")
            return pl.DataFrame()


    def compile_files_to_parquet(self, source: str=str(), target: str='data/level1', dtm: str='dtm', by_year: bool=True):
        """
        Harvest a foldedr and its sub-folders and compile the data found in .parquet files. 
        At this point, 2 file formats are supported, namely the Aurora file format and the mkndaq file format.
        The Aurora file format concerns files stored by the instrument, the mkndaq file format (v1) is the format generated by mkndaq.

        Args:
            source (str, optional): Folder to harvest. Defaults to str().
            target (str, optional): Folder for the resulting .parquet files. Defaults to 'data/level1'.
            dtm (str, optional): key of the timestamp column. Defaults to 'dtm'.
            by_year (bool, optional): Should .parquet files be organized by year. Defaults to True. NB: Currently not implemented.
        """          
        try:
            source = os.path.join(self.root, self.incoming, self.name)

            df_aurora = pl.DataFrame()
            df_mkndaq = pl.DataFrame()
            if os.path.exists(source):
                for root, dirs, files in os.walk(source):
                    for file in files:
                        if 'ne300' in file:
                            _mkndaq = self.extract_to_dataframe(os.path.join(root, file))
                            if not _mkndaq.is_empty():
                                df_mkndaq = pl.concat([df_mkndaq, _mkndaq], how='diagonal')
                                dst = os.path.join(root, file).replace(self.incoming, self.archive)
                            else:
                                dst = os.path.join(root, file).replace(self.incoming, self.issues)

                        else:
                            _aurora = self.extract_to_dataframe(os.path.join(root, file))
                            if not _aurora.is_empty():
                                df_aurora = pl.concat([df_aurora, _aurora], how='diagonal')
                                dst = os.path.join(root, file).replace(self.incoming, self.archive)
                            else:
                                dst = os.path.join(root, file).replace(self.incoming, self.issues)

                        os.makedirs(os.path.dirname(dst), exist_ok=True)
                        shutil.move(src=os.path.join(root, file), dst=dst)
            
            # verify if .parquet already exist, amend and retain unique values
            for file, df in {'ne300_aurora.parquet': df_aurora, 'ne300_mkndaq.parquet': df_mkndaq}.items():
                target_file = os.path.join(target, file)
                if os.path.exists(target_file):
                    df = pl.concat([pl.read_parquet(target_file), 
                                       df], how='diagonal')
                df = df.unique().sort(by=dtm)
                df.write_parquet(target_file)

        except Exception as err:
            self.logger.error(err)                
            pass
