# %%
# Author: joerg.klausen@meteoswiss.ch
import os
import re
import datetime
import json
import matplotlib.pyplot as plt
import pandas as pd
import polars as pl
import numpy as np

# %%
def count_files(path: str, pattern: str, dte: datetime=None) -> int:
    """Count the number of files matching <pattern> in <path>

    Args:
        path (str): Path to search.
        pattern (str): regex describing the files to count.

    Returns:
        int: Number of files matching criteria
    """
    count = 0

    if re.search(r"d\{7\}\.", pattern) and dte:
        regex_pattern = re.compile(f'(?=.*{pattern})(?=.*{dte.strftime("%j%Y")})')
    elif dte:
        regex_pattern = re.compile(f'(?=.*{pattern})(?=.*{dte.strftime("%Y%m%d")})')
    else:
        regex_pattern = re.compile(pattern)

    for root, dirs, files in os.walk(path):
        for file in files:
            if regex_pattern.match(file):
                count += 1

    return count

#%%
def sum_pairwise(list_of_lists):
    """Given a list of lists of numbers, return a list of pairwise sums"""
    totals = list_of_lists[0]
    foo = lambda l1, l2: [a + b for a, b in zip(l1, l2)]
    for lst in list_of_lists[1:]:
        totals = foo(totals, lst)
    return totals


# %%
def get_file_coverage(cfg: dict, days: int) -> dict:
    """Count number of files conforming to <pattern> in a directory structure organized by yyyy/mm/dd, covering a given number of days.

    Args:
        cfg (dict): Configuration, for each instrument or data type. Described in mch-config.yml.
        days (int): Number of days in the past.
        save (bool): Should output be persistent in a file written to <root>?. Defaults to True.
    Returns:
        dict: JSON object and (optionally) JSON file with expected number of files per day and actual number of files for each day.
    """
    dates = [(datetime.datetime.now() - datetime.timedelta(days=d)) for d in range(days, 0, -1)] + [datetime.datetime.now()]
    stats = {"root": cfg["root"]}
    stats["dates"] = [dte.strftime("%Y-%m-%d") for dte in dates]
    

    # df = pl.DataFrame({"Dates": [dte.strftime("%Y-%m-%d") for dte in dates]})

    for folder in cfg["folders"]:
        stats[folder] = {}
        stats[folder]["expected"] = cfg[folder]["expected"]
        stats[folder]["found"] = {}
        found_in_branches = []
        for branch in cfg["branches"]:
            base_path = os.path.join(cfg["root"], branch, folder)
            pattern = cfg[folder]["pattern"]
            found = []
            for date in dates:
                if os.path.exists(path:=os.path.join(base_path, str(date.year), '{:02}'.format(date.month), '{:02}'.format(date.day))):
                    n = count_files(path=path, pattern=pattern)
                elif os.path.exists(path:=os.path.join(base_path, str(date.year), '{:02}'.format(date.month))):
                    n = count_files(path=path, pattern=pattern, dte=date)
                elif os.path.exists(path:=os.path.join(base_path, str(date.year))):
                    n = count_files(path=path, pattern=pattern, dte=date)              
                else:
                    n = 0
                found.append(n)
                # totals.append(n)
            stats[folder]["found"][branch] = found
            found_in_branches = found_in_branches + [found]
        stats[folder]["found"]["totals"] = sum_pairwise(found_in_branches)

    return stats


# %%
def __barplot_file_coverage(stats: dict) -> None:
    """Bar plot of file coverage statistics generated by get_file_coverage()

    Args:
        stats (dict): JSON object with expected number of files per day and actual number of files for each day.
    """
    x = np.arange(len(stats["dates"]))
    w = 0.15 # bar width

    fig, ax = plt.subplots()

    m = 0
    for key, values in stats.items():
        if key not in ["root", "dates"]:
            expected = [stats[key]["expected"] for i in x]
            missing = [i - j for i, j in zip(expected, stats[key]["found"]["totals"])]
            x_values = x + w*m
            y_values = values["found"]["totals"]
            #  [TODO] specify yerr as vertical bars between found and expected
            # yerr = np.array([missing, expected])
            found = ax.bar(x_values, y_values, w)
            ax.bar_label(found, rotation=90, label_type='center', fontsize=8)
            m += 1

    fig.suptitle(f"Files found under {stats['root']}")
    ax.set_title(f"including: /incoming, /archive, /issues")
    ax.set_ylabel("Files per day")
    ax.set_xlabel("Date")
    ax.set_xticks(x, stats["dates"], rotation=30)
    ax.legend(labels=[i for i in stats.keys()][2:], loc='best', fontsize=8)

    fig.show()

    return None

# %%
def __lineplot_file_coverage(stats) -> None:
    """Line plot of file coverage statistics generated by get_file_coverage()

    Args:
        stats (dict): JSON object with expected number of files per day and actual number of files for each day.
    """
    x = np.arange(len(stats["dates"]))

    fig, ax = plt.subplots()

    for key, values in stats.items():
        if key not in ["root", "dates"]:
            ax.plot(stats["dates"], stats[key]["found"]["totals"])
            ax.set_label(key)

    ax.set_title(f"Files found under {stats['root']}")
    ax.set_ylabel("Files per day")
    ax.set_xlabel("Date")
    ax.set_xticks(x, stats["dates"], rotation=30)
    ax.legend(labels=[i for i in stats.keys()][2:], loc='best', fontsize=8)

    return None


def plot_coverage(stats: dict=None, cfg: dict=None, days: int=7) -> None:
    """Plot file coverage statistics generated by get_file_coverage()

    Args:
        stats (dict): JSON object with expected number of files per day and actual number of files for each day.
        cfg (dict): Configuration, for each instrument or data type. Described in mch-config.yml.
        days (int): Number of days to consider. Defaults to 7.
    """
    if stats is None:
        if cfg:
            stats = get_file_coverage(cfg=cfg, days=days, simple=True)
        else:
            raise ValueError("Either 'stats', or 'cfg' and 'days' must be specified.")

    if days > 3:
        __lineplot_file_coverage(stats=stats)
    else:
        __barplot_file_coverage(stats=stats)

    return None

# %%
def print_coverage(stats: dict=None, cfg: dict=None, days: int=7) -> pd.DataFrame:
    """Print file coverage statistics generated by get_file_coverage() as a simple table

    Args:
        stats (dict): JSON object with expected number of files per day and actual number of files for each day.
        cfg (dict): Configuration, for each instrument or data type. Described in mch-config.yml.
        days (int): Number of days to consider. Defaults to 7.
    """
    if stats is None:
        if cfg:
            stats = get_file_coverage(cfg=cfg, days=days)
        else:
            raise ValueError("Either 'stats', or 'cfg' and 'days' must be specified.")

    dates = stats['dates']
    columns = [i for i in stats.keys()][2:]
    expected_values = [stats[column]['expected'] for column in columns]
    totals_values = {column: stats[column]['found']['totals'] for column in columns}

    # create a DataFrame
    df = pd.DataFrame(totals_values, index=dates)

    # add the 'expected' row as the first row
    df = pd.concat([pd.DataFrame([expected_values], columns=columns), df])
    
    df.reset_index(inplace=True)
    df.loc[0, "index"] = "expected"

    return df 


# %%
if __name__ == "__main__":
    pass


